# Generated by Django 6.1.1 on 2026-09-09 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WinSid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid_string', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'win_sid',
            },
        ),
        migrations.CreateModel(
            name='WinVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'win_volume',
            },
        ),
        migrations.CreateModel(
            name='WinLocalGroup',
            fields=[
                ('sid', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, related_name='local_group', serialize=False, to='winfs.winsid')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'win_local_group',
            },
        ),
        migrations.CreateModel(
            name='WinSecurityDescriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('se_dacl_protected', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(db_column='owner_sid_id', on_delete=django.db.models.deletion.RESTRICT, related_name='owned_descriptors', to='winfs.winsid')),
            ],
            options={
                'db_table': 'win_security_descriptor',
            },
        ),
        migrations.CreateModel(
            name='WinNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='winfs.winnode')),
                ('security_descriptor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='node', to='winfs.winsecuritydescriptor')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='nodes', to='winfs.winvolume')),
            ],
            options={
                'db_table': 'win_node',
            },
        ),
        migrations.CreateModel(
            name='WinSidMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(db_column='member_sid_id', on_delete=django.db.models.deletion.RESTRICT, related_name='group_memberships', to='winfs.winsid')),
                ('group', models.ForeignKey(db_column='group_sid_id', on_delete=django.db.models.deletion.RESTRICT, related_name='memberships', to='winfs.winlocalgroup')),
            ],
            options={
                'db_table': 'win_sid_member',
            },
        ),
        migrations.CreateModel(
            name='WinPrincipal',
            fields=[
                ('sid', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, related_name='principal', serialize=False, to='winfs.winsid')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='win_principal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'win_principal',
            },
        ),
        migrations.CreateModel(
            name='WinAce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ace_order', models.IntegerField()),
                ('ace_type', models.CharField(max_length=8)),
                ('access_mask', models.BigIntegerField()),
                ('flag_oi', models.BooleanField(default=False)),
                ('flag_ci', models.BooleanField(default=False)),
                ('flag_np', models.BooleanField(default=False)),
                ('flag_io', models.BooleanField(default=False)),
                ('flag_inherited', models.BooleanField(default=False)),
                ('trustee', models.ForeignKey(db_column='trustee_sid_id', on_delete=django.db.models.deletion.RESTRICT, related_name='aces', to='winfs.winsid')),
                ('descriptor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='aces', to='winfs.winsecuritydescriptor')),
            ],
            options={
                'db_table': 'win_ace',
                'indexes': [models.Index(fields=['descriptor', 'ace_order'], name='win_ace_descrip_8e9368_idx')],
                'constraints': [models.UniqueConstraint(fields=('descriptor', 'ace_order'), name='win_ace_descriptor_order'), models.CheckConstraint(condition=models.Q(('ace_type__in', ('allow', 'deny'))), name='win_ace_type'), models.CheckConstraint(condition=models.Q(('access_mask__gte', 0)), name='win_ace_mask_nonneg')],
            },
        ),
        migrations.CreateModel(
            name='WinStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='streams', to='winfs.winnode')),
            ],
            options={
                'db_table': 'win_stream',
                'constraints': [models.UniqueConstraint(fields=('node', 'name'), name='win_stream_node_name')],
            },
        ),
        migrations.AddIndex(
            model_name='winnode',
            index=models.Index(fields=['parent'], name='win_node_parent__5e3734_idx'),
        ),
        migrations.AddIndex(
            model_name='winnode',
            index=models.Index(fields=['security_descriptor'], name='win_node_securit_dc5392_idx'),
        ),
        migrations.AddIndex(
            model_name='winnode',
            index=models.Index(fields=['volume'], name='win_node_volume__a33fae_idx'),
        ),
        migrations.AddConstraint(
            model_name='winnode',
            constraint=models.UniqueConstraint(fields=('volume', 'parent', 'name'), name='win_node_sibling_name'),
        ),
        migrations.AddConstraint(
            model_name='winnode',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('file', 'folder'))), name='win_node_kind'),
        ),
        migrations.AddConstraint(
            model_name='winsidmember',
            constraint=models.UniqueConstraint(fields=('group', 'member'), name='win_sid_member_pk_pair'),
        ),
        migrations.AddConstraint(
            model_name='winsidmember',
            constraint=models.CheckConstraint(condition=models.Q(('group_id', models.F('member_id')), _negated=True), name='win_sid_member_not_self'),
        ),
    ]
